config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout' }
  resources :users

  resources :chat_rooms, only: [:new, :create, :show, :index, :destroy]

  mount ActionCable.server => '/cable'

  root 'chat_rooms#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat_room.rb
class ChatRoom < ApplicationRecord
  belongs_to :user
  has_many :messages, dependent: :destroy

  validates :title, presence: true, length: {minimum: 1, maximum: 50}
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :chat_room

  validates :body, presence: true, length: {minimum: 1, maximum: 1000}

  after_create_commit { MessageBroadcastJob.perform_later(self) }


  # TODO make it so messages are deleted after 24 hours of posting.
  # TODO make messages specific to user's geographical location i.e. only show messages from NYC users when the user is in NYC.

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :first_name, length: { maximum: 50 }
  validates :last_name, length: { maximum: 50 }
  validates :city, length: { maximum: 50 }
  validates :about, length: { maximum: 250 }
  validates :interests, length: { maximum: 125 }

  has_many :chat_rooms, dependent: :destroy
  has_many :messages, dependent: :destroy

  def name
    if first_name == ""
      email.split('@')[0]
    else
      first_name
    end
  end

  def full_name
    first_name + " " + last_name
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!

  include DeviseWhitelist

end

app/controllers/chat_rooms_controller.rb
class ChatRoomsController < ApplicationController
  def index
    @chat_rooms = ChatRoom.all
  end

  def new
    @chat_room = ChatRoom.new
  end

  def create
    @chat_room = current_user.chat_rooms.build(chat_room_params)
    if @chat_room.save
      flash[:success] = 'Chat room added!'
      redirect_to chat_rooms_path
    else
      render 'new'
    end
  end

  def show
    @chat_room = ChatRoom.includes(:messages).find_by(id: params[:id])
    @message = Message.new
  end

  def destroy
    @chat_room = ChatRoom.find(params[:id])
    if @chat_room.present?
      @chat_room.destroy
    end
    redirect_to root_url
  end

  private

  def chat_room_params
    params.require(:chat_room).permit(:title, :description)
  end
end

app/controllers/concerns/devise_whitelist.rb
module DeviseWhitelist
extend ActiveSupport::Concern

 included do
  before_action :configure_permitted_parameters, if: :devise_controller?
end

def configure_permitted_parameters
  devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :email, :password, :about, :city, :state, :interests])
  devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :email, :password, :about, :city, :state, :interests])
end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:first_name, :last_name, :about, :city, :state, :interests)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def gravatar_for(user, opts = {})
    opts[:alt] = user.name
    image_tag "https://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(user.email)}?s=#{opts.delete(:size) { 40 }}",
              opts
  end

  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "ChatterBox"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/views/chat_rooms/_chat_room.html.erb
<%= link_to chat_room_path(chat_room), class: "card room", align: "center" do %>

<div class="card-header btn-group">
  <small class="chat-date text-muted">
    Posted <%= "#{time_ago_in_words(chat_room.created_at)} ago" %>
  </small>
  <div class="btn-group chat-btns">
  <button type="button" class="btn btn-light room-options" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" data-toggle="tooltip" data-placement="top" title="More options">
    <i class="fas fa-ellipsis-h"></i>
  </button>
  <div class="dropdown-menu dropdown-menu-right">
    <button class="dropdown-item" type="button">Hide This Room</button>
    <button class="dropdown-item" type="button">Bookmark This Room</button>
    <button class="dropdown-item" type="button">Something else here</button>
  </div>
</div>
</div>
<h2><%= "#{chat_room.title}" %></h2>
<p><strong><%= "#{chat_room.messages.size}" %></strong>

  <% if chat_room.messages.size > 1 || chat_room.messages.size == 0  # Checks to see how many messages in each room %>
  Messages
    <% else %>
  Message
    <% end %>
</p>
<% end %>

app/views/chat_rooms/index.html.erb
<% provide(:title, "Rooms") %>

<div id="room-index">
  <!-- Display user geological location -->
  <h1 align="center">Chat rooms in <%= request.location.city %></h1>
  <br>
  <% if @chat_rooms.size < 1 # Checks to see if room index is empty or not.%>
  <h3 id="no-room" align="center">Looks like this place is a little empty.  Why don't you make a room?</h3>
  <p class="lead-0" align="center"><%= link_to 'New chat room', new_chat_room_path, class: 'new-buttons new-chat-btn' %></p>
  <% else %>
  <ul class="row room-row">
    <p class="lead"><%= link_to 'New chat room', new_chat_room_path, class: 'new-buttons new-chat-btn' %></p>
    <%= render @chat_rooms.reverse %>
  </ul>
  <% end %>
  <br>
</div>

app/views/chat_rooms/new.html.erb
<% provide(:title, "New Chat Room") %>

<div class="card form-align">
<h1>Add chat room</h1>

<%= form_for @chat_room do |f| %>
  <div class="form-group">
    <%= f.text_field :title, autofocus: true, class: 'form-control', placeholder: "Title" %>
  </div>

  <div class="form-group">
    <small class="text-muted">Optional:</small>
    <%= f.text_area :description, class: 'form-control', rows: 2, placeholder: "Description" %>
  </div>

  <%= f.submit "Create that room!", class: 'new-buttons' %>
<% end %>
</div>

app/views/chat_rooms/show.html.erb
<% provide(:title, @chat_room.title) %>

<div class="chat-room">
  <span class="card">
    <h1 class="card-header"><%= @chat_room.title %>
      <div class="float-right">
        <button type="button" class="btn btn-light room-options" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fas fa-ellipsis-h"></i>
        </button>
        <div class="dropdown-menu dropdown-menu-right">
          <button class="dropdown-item" type="button">Hide This Room</button>
          <button class="dropdown-item" type="button">Bookmark This Room</button>
          <button class="dropdown-item" type="button">Something else here</button>
        </div>
      </div>
    </h1>
    <p><%= @chat_room.description %></p>

    <% if @chat_room.messages.size < 1 %>
    <div id="messages" data-chat-room-id="<%= @chat_room.id %>">
      <h2 id="no-msg">Go ahead, type something in!</h2>
    </div>
    <% else %>
    <div id="messages" data-chat-room-id="<%= @chat_room.id %>">
      <%= render @chat_room.messages %>
    </div>
    <% end %>
  </span>
  <%= form_for @message, url: '#' do |f| %>
  <span class="msg-input">
    <small class="text-muted">From 1 to 1000 characters</small>
    <div class="input-group mb-3">
      <%= f.text_field :body, class: "form-control", rows: 1, placeholder: "Message", aria_label:"Message", aria_describedby: "basic-addon2", autofocus: "autofocus", autocomplete: "off" %>
      <div class="input-group-append">
        <%= f.submit "Send", id: "send-buttons" %>
      </div>
    </div>
  </span>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <title>ChatterBox</title>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">
</head>

<body>

  <nav class="navbar">
    <%= link_to 'ChatterBox', root_path, class: 'logo' %>

    <ul class="nav nav-pills pull-xs-right">
      <% if user_signed_in? %>

      <div class="dropdown profile-button">
        <span class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <%= gravatar_for current_user, size: "40px", class: "avatar"; %>
          <% if current_user.first_name == "" %>
          <span class="menu-label"><strong><%= current_user.name %></strong></span>
          <% else %>
          <span class="menu-label"><strong><%= current_user.full_name %></strong></span>
          <% end %>
        </span>

        <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
          <%= link_to 'Profile', current_user, class: "dropdown-item" %>
          <%= link_to "Account Settings", edit_user_registration_path, class: "dropdown-item" %>
          <%= link_to 'Help', '#', class: "dropdown-item" %>
          <div class="dropdown-divider"></div>
          <%= link_to 'Logout', destroy_user_session_path, class: "dropdown-item", method: :delete %>
        </div>
      </div>

      <% else %>
      <li class="nav-item">

      </li>
      <% end %>
    </ul>
  </nav>
  <% if notice %>
    <p class="notice alert-success" align="center" role="notice"><%= notice %></p>
  <% end %>
  <% if alert %>
  <p class="alert alert-danger" align="center" role="alert"><%= alert %></p>
    <% end %>
  <div class="page-wrap">
    <div class="container">
      <%= yield %>
    </div>
  </div>

  <footer class="site-footer">
    <p style="color:white;">ChatterBox</p>
  </footer>
</body>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</html>

app/views/messages/_message.html.erb
<div class="msg-box">
  <div class="msg-card">
    <div class="card-block">
      <div class="row">
        <div class="col-md-1">
          <%= gravatar_for message.user %>
        </div>
        <div class="col-md-11">
          <p class="card-text">
            <small class="text-muted">
              <%= message.user.name %> about <em><%= "#{time_ago_in_words(message.created_at)} ago" %></em>
            </small>
            <br>
            <%= message.body %>
          </p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/_user.html.erb
<% provide(:title, @user.full_name) %>

<div class="profile card" align="center">

  <h1 class="card-header profile-header"><%= @user.first_name %> <%= @user.last_name %></h1>
  <%= gravatar_for @user, size: "300px"; %>
  <hr>

  <!-- TODO display user demographics and information -->

  <ul style="list-style-type:none">
    <li><p><%= @user.email %></p></li>

    <% if @user.city && @user.state != nil %>
      <li><p>Located in: <a target="_blank" href="https://www.google.com/maps/place/<%= @user.city %>, <%= @user.state %>"><%= @user.city + ", " + @user.state %></a></p></li>
    <% else %>
      <%= @user.city || @user.state %>
    <% end %>

    <li><p><%= @user.about %></p></li>
    <li><p><%= @user.interests %></p></li>
  </ul>

  <% if @user == current_user %>
  <%= link_to "Edit Info", edit_user_registration_path, class: "new-buttons" %>
  <% end %>

</div>

app/views/users/show.html.erb
<%= render "user" %>